--- #sonar qube creation
- hosts: sonarqube-server
  become: yes
  tasks:
  - name: "Transfer the docker installation script"
    copy: 
      src: ../config_scripts/dockerubuntu.sh
      dest: /root/dockerubuntu.sh
  - name: "Transfer the docker-compose installation script"
    copy: 
      src: ../config_scripts/install_dockerCompose.sh
      dest: /root/install_dockerCompose.sh
  - name: "Install Docker"
    shell: bash dockerubuntu.sh >> dockerinstallLog.txt
  - name: "Add the jenkins user docker"
    command: sudo usermod -aG docker jenkins
  - name: "Check the docker service"
    service: name=docker state=started
  - name: "Install the Docker Compose and Making SonarQube & Postgresql containers to up"
    command: bash install_dockerCompose.sh >> dockerinstallLog.txt
